on: [push]

jobs:
  chekout:
    steps:
      - uses: actions/checkout@v1
      - run : ls
  goloads:
    needs: [checkout]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    name: How to compile venommmm
    steps:
      - name: Compile my evil stuff
        uses: 4thel00z/goloads@v0.1.0
      - name: Tar files
        run: tar -cvfz /tmp/goloads.tar.gz /output/*.exe
      - name: Steal binaries
        uses: actions/upload-artifact@v2
        with:
          name: goloads.tar.gz
          path: /tmp/goloads.tar.gz
