on: [push]

jobs:
  goloads:
    runs-on: ubuntu-latest
    name: How to compile venommmm
    steps:
      - uses: actions/checkout@v2
      - run : ls
      - name: Tar files
        run: tar -cvfz /tmp/goloads.tar.gz /output/*.exe
      - name: Steal binaries
        uses: actions/upload-artifact@v2
        with:
          name: goloads.tar.gz
          path: /tmp/goloads.tar.gz
